/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controlador.Utilitaria;
import Modelo.Cliente;
import Modelo.Reserva;
import Modelo.Vehiculo;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Esta clase (Java Form) hereda de JFrame, esta ventana permite al usuario filtrar las reservas por 
 * fecha de inicio
 * @since 30/10/2020
 * @version 1.0
 * @author Fabricio Delgado Morales, Johan Alonso Calvo Vargas, Mariana Hidalgo Sandoval, 
 * Silvia Melissa Rodríguez Fernández
 * 
 */

public class FiltroFecha extends javax.swing.JFrame {
        static FiltroFecha frameRegistrarOperador = new FiltroFecha();
        static String PlacaTexto="";
        static Reserva ReservaSeleccionada;
    /**
     * Creates new form FiltroPuntoRecogida
     */
    public FiltroFecha() {
        initComponents();
        ReservasPorFecha.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        BotónConfirmar = new javax.swing.JButton();
        BotónAtrás = new javax.swing.JButton();
        ReservasPorFecha = new javax.swing.JComboBox<>();
        botonBuscarFecha = new javax.swing.JButton();
        CalendarField = new com.toedter.calendar.JDateChooser();

        jToggleButton2.setText("jToggleButton2");

        jToggleButton1.setText("jToggleButton1");

        setTitle(" Filtrar Reserva por Fecha");
        setLocation(new java.awt.Point(0, 0));

        BotónConfirmar.setText("Consultar");
        BotónConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotónConfirmarActionPerformed(evt);
            }
        });

        BotónAtrás.setText("Atrás");
        BotónAtrás.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotónAtrásActionPerformed(evt);
            }
        });

        ReservasPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservasPorFechaActionPerformed(evt);
            }
        });

        botonBuscarFecha.setText("Buscar");
        botonBuscarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotónConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReservasPorFecha, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CalendarField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscarFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotónAtrás, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(BotónAtrás)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CalendarField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBuscarFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(ReservasPorFecha)
                .addGap(31, 31, 31)
                .addComponent(BotónConfirmar)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotónAtrásActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotónAtrásActionPerformed
        frameRegistrarOperador.setVisible(false); 
        CalendarField.setDate(null);
        ReservasPorFecha.setEnabled(false);
    }//GEN-LAST:event_BotónAtrásActionPerformed

    private void BotónConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotónConfirmarActionPerformed
        if(ReservasPorFecha.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "No hay una reserva seleccionada");
        } else{
            ReservaSeleccionada = (Reserva) ReservasPorFecha.getSelectedItem();
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

            DatosCliente.frameDatosCliente.setLocation(dim.width/2-
                    DatosCliente.frameDatosCliente.getSize().width/2, dim.height/2-
                            DatosCliente.frameDatosCliente.getSize().height/2);

            Inicio.VentanaConsultarReserva(false); 
            Inicio.VentanaReserva(true);

            Inicio.frameRes.ContenidoTextoID.setText(String.valueOf(ReservaSeleccionada.getNumeroFactura()));
            Inicio.frameRes.ContenidoTextoRecogida.setText(ReservaSeleccionada.getSedeRecogida());
            Inicio.frameRes.ContenidoTextoEntrega.setText(ReservaSeleccionada.getSedeEntrega());
            Inicio.frameRes.ContenidoTextoInicio.setText(
                    Utilitaria.formatoFecha(ReservaSeleccionada.getFechaInicio()));
            Inicio.frameRes.ContenidoTextoFinal.setText(
                    Utilitaria.formatoFecha(ReservaSeleccionada.getFechaFinalizacion()));
            Inicio.frameRes.ContenidoTextoSolicitud.setText(
                    Utilitaria.formatoFecha(ReservaSeleccionada.getFechaSolicitud()));
            Inicio.frameRes.ContenidoTextoOperador.setText(ReservaSeleccionada.getOperador().toString());
            Vehiculo Auto = ReservaSeleccionada.getVehiculoSeleccionado();
            Cliente Persona = ReservaSeleccionada.getClienteRelacionado();
            Inicio.frameRes.ContenidoTextoCliente.setText(ReservaSeleccionada.getClienteRelacionado().toString());
            TablaServiciosReserva.frameTablaServiciosPorReserva.agregarServicios
                (ReservaSeleccionada.getArrayServicios());
            Detalles.TextoPlacaSeleccionado.setText(Auto.getPlaca());
            Detalles.TextoAñoSeleccionado.setText(String.valueOf(Auto.getAñoFabricacion()));
            Detalles.TextoColorSeleccionado.setText(Auto.getColor());
            Detalles.TextoMarcaSeleccionado.setText(Auto.getMarca());
            Detalles.TextoKilometrajeSeleccionado.setText(String.valueOf(Auto.getKilometraje()));
            Detalles.TextoKCapacidadSeleccionado.setText(String.valueOf(Auto.getCapacidad()));
            Detalles.TextoPuertasSeleccionado.setText(String.valueOf(Auto.getNumeroPuertas()));
            Detalles.TextoMPGSeleccionado.setText(String.valueOf(Auto.getMpg())); 
            Detalles.TextoSedeSeleccionado.setText(Auto.getSede());
            Detalles.TextoCostoeleccionado.setText(String.valueOf(Auto.getCostoDiario())+"/d");
            Detalles.TextoCapacidadSeleccionado.setText(String.valueOf(Auto.getCapacidad()));
            Detalles.TextoTipoTransimisionSeleccionado.setText(Auto.getTipoTransmision().toString());
            Detalles.TextoEstadoSeleccionado.setText(Auto.getEstado().toString());
            Detalles.TextoVinSeleccionado.setText(Auto.getNumeroVin().toString());

            ImageIcon imagenSeleccionada = new ImageIcon(Auto.getImagen());
            Detalles.TextoImagenSeleccionado.setIcon(imagenSeleccionada);
            Image imagenSinEscala = imagenSeleccionada.getImage();
            Image imagenEscalada = imagenSinEscala.getScaledInstance(256, 144, Image.SCALE_SMOOTH);
            imagenSeleccionada.setImage(imagenEscalada);
            Detalles.TextoImagenSeleccionado.setIcon(imagenSeleccionada);
            Detalles.TextoImagenSeleccionado.setText("Sin fotografía");

            Object[] filas= {};
            filas = Auto.getListaServiciosRelacionados().toArray();
            System.out.println(Auto.getListaServiciosRelacionados());
            TablaServiciosAsociados.ModificarTablaServiciosAsociados(filas);

            DatosCliente.frameDatosCliente.textNombreCliente.setText("Nombre: "+Persona.getNombreCompleto());
            DatosCliente.frameDatosCliente.textCedula.setText("Cédula: "+Persona.getCedula());
            DatosCliente.frameDatosCliente.textoCorreo.setText("Correo: "+Persona.getCorreoElectronico());
            DatosCliente.frameDatosCliente.textoDireccion.setText("Correo: "+Persona.getDireccionExacta());
            DatosCliente.frameDatosCliente.textoLicencia.setText("Licencia: "+ Persona.getNumeroLicencia() + 
                    " ("+Persona.getTipoLicencia() +") " + "("+ 
                        Utilitaria.formatoFecha(Persona.getFechaEmisionLicencia()) + " - " + 
                            Utilitaria.formatoFecha(Persona.getFechaExpiracionLicencia()) +")");

            imagenSeleccionada = new ImageIcon(Persona.getImagen());
            DatosCliente.frameDatosCliente.img2.setIcon(imagenSeleccionada);
            imagenSinEscala = imagenSeleccionada.getImage();
            imagenEscalada = imagenSinEscala.getScaledInstance(160, 90, Image.SCALE_SMOOTH);
            imagenSeleccionada.setImage(imagenEscalada);
            DatosCliente.frameDatosCliente.img2.setIcon(imagenSeleccionada);
            DatosCliente.frameDatosCliente.img2.setText("Sin fotografía");
            Inicio.VentanaReserva(true);
            frameRegistrarOperador.setVisible(false);
            CalendarField.setDate(null);
            ReservasPorFecha.setEnabled(false);
            ReservasPorFecha.setSelectedIndex(0);
        
        
        }
    }//GEN-LAST:event_BotónConfirmarActionPerformed

    private void ReservasPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservasPorFechaActionPerformed
        ReservaSeleccionada=(Reserva)ReservasPorFecha.getSelectedItem();
    }//GEN-LAST:event_ReservasPorFechaActionPerformed
  
    private void botonBuscarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarFechaActionPerformed
            if(CalendarField.getCalendar()!=null){
                ReservasPorFecha.setEnabled(true);
                DefaultComboBoxModel mod= new DefaultComboBoxModel(Inicio.adminApp.filtrarReservaInicio
                    (CalendarField.getCalendar()).toArray());
                ReservasPorFecha.setModel(mod);
                
            }else{
                ReservasPorFecha.setEnabled(false);
                ReservasPorFecha.setSelectedIndex(0);
            }
    }//GEN-LAST:event_botonBuscarFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotónAtrás;
    private javax.swing.JButton BotónConfirmar;
    private com.toedter.calendar.JDateChooser CalendarField;
    private javax.swing.JComboBox<Reserva> ReservasPorFecha;
    private javax.swing.JButton botonBuscarFecha;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
