/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controlador.Utilitaria;
import Modelo.Cliente;
import Modelo.Reserva;
import Modelo.Vehiculo;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Esta clase (Java Form) hereda de JFrame, esta ventana permite al usuario filtrar las reservas por placa del vehículo en ña reserva
 * @since 30/10/2020
 * @version 1.0
 * @author Fabricio Delgado Morales, Johan Alonso Calvo Vargas, Mariana Hidalgo Sandoval, Silvia Melissa Rodríguez Fernández
 * 
 */
public class FiltroPlaca extends javax.swing.JFrame {
        static FiltroPlaca frameRegistrarOperador = new FiltroPlaca();
        static String PlacaTexto="";
        static Reserva ReservaSeleccionada;
    /**
     * Creates new form FiltroPuntoRecogida
     */
    public FiltroPlaca() {
        initComponents();
        ReservasDisponibles.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        botonConsultar = new javax.swing.JButton();
        BotónAtrás = new javax.swing.JButton();
        ReservasDisponibles = new javax.swing.JComboBox<>();
        TextFieldPlaca = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();

        jToggleButton2.setText("jToggleButton2");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 250));

        botonConsultar.setText("Consultar");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });

        BotónAtrás.setText("Atrás");
        BotónAtrás.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotónAtrásActionPerformed(evt);
            }
        });

        ReservasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservasDisponiblesActionPerformed(evt);
            }
        });

        TextFieldPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPlacaActionPerformed(evt);
            }
        });

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReservasDisponibles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextFieldPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscar)))
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(BotónAtrás, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(BotónAtrás)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(ReservasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(botonConsultar)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotónAtrásActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotónAtrásActionPerformed
        frameRegistrarOperador.setVisible(false); 
        TextFieldPlaca.setText("");
        ReservasDisponibles.setEnabled(false);
        
    }//GEN-LAST:event_BotónAtrásActionPerformed

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        PlacaTexto = TextFieldPlaca.getText();
        if(PlacaTexto.equals("")){
            JOptionPane.showMessageDialog(this, "Elementos incompletos");
        }else{
            ReservaSeleccionada = (Reserva) ReservasDisponibles.getSelectedItem();
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

            DatosCliente.frameDatosCliente.setLocation(dim.width/2-
                    DatosCliente.frameDatosCliente.getSize().width/2, dim.height/2-
                            DatosCliente.frameDatosCliente.getSize().height/2);

            Inicio.VentanaConsultarReserva(false); 
            Inicio.VentanaReserva(true);

            Inicio.frameRes.ContenidoTextoID.setText(String.valueOf(ReservaSeleccionada.getNumeroFactura()));
            Inicio.frameRes.ContenidoTextoRecogida.setText(ReservaSeleccionada.getSedeRecogida());
            Inicio.frameRes.ContenidoTextoEntrega.setText(ReservaSeleccionada.getSedeEntrega());
            Inicio.frameRes.ContenidoTextoInicio.setText(
                    Utilitaria.formatoFecha(ReservaSeleccionada.getFechaInicio()));
            Inicio.frameRes.ContenidoTextoFinal.setText(
                    Utilitaria.formatoFecha(ReservaSeleccionada.getFechaFinalizacion()));
            Inicio.frameRes.ContenidoTextoSolicitud.setText(
                    Utilitaria.formatoFecha(ReservaSeleccionada.getFechaSolicitud()));
            Inicio.frameRes.ContenidoTextoOperador.setText(ReservaSeleccionada.getOperador().toString());
            Vehiculo Auto = ReservaSeleccionada.getVehiculoSeleccionado();
            Cliente Persona = ReservaSeleccionada.getClienteRelacionado();
            Inicio.frameRes.ContenidoTextoCliente.setText(ReservaSeleccionada.getClienteRelacionado().toString());
            TablaServiciosReserva.frameTablaServiciosPorReserva.agregarServicios
                (ReservaSeleccionada.getArrayServicios());
            Detalles.TextoPlacaSeleccionado.setText(Auto.getPlaca());
            Detalles.TextoAñoSeleccionado.setText(String.valueOf(Auto.getAñoFabricacion()));
            Detalles.TextoColorSeleccionado.setText(Auto.getColor());
            Detalles.TextoMarcaSeleccionado.setText(Auto.getMarca());
            Detalles.TextoKilometrajeSeleccionado.setText(String.valueOf(Auto.getKilometraje()));
            Detalles.TextoKCapacidadSeleccionado.setText(String.valueOf(Auto.getCapacidad()));
            Detalles.TextoPuertasSeleccionado.setText(String.valueOf(Auto.getNumeroPuertas()));
            Detalles.TextoMPGSeleccionado.setText(String.valueOf(Auto.getMpg())); 
            Detalles.TextoSedeSeleccionado.setText(Auto.getSede());
            Detalles.TextoCostoeleccionado.setText(String.valueOf(Auto.getCostoDiario())+"/d");
            Detalles.TextoCapacidadSeleccionado.setText(String.valueOf(Auto.getCapacidad()));
            Detalles.TextoTipoTransimisionSeleccionado.setText(Auto.getTipoTransmision().toString());
            Detalles.TextoEstadoSeleccionado.setText(Auto.getEstado().toString());
            Detalles.TextoVinSeleccionado.setText(Auto.getNumeroVin().toString());

            ImageIcon imagenSeleccionada = new ImageIcon(Auto.getImagen());
            Detalles.TextoImagenSeleccionado.setIcon(imagenSeleccionada);
            Image imagenSinEscala = imagenSeleccionada.getImage();
            Image imagenEscalada = imagenSinEscala.getScaledInstance(256, 144, Image.SCALE_SMOOTH);
            imagenSeleccionada.setImage(imagenEscalada);
            Detalles.TextoImagenSeleccionado.setIcon(imagenSeleccionada);
            Detalles.TextoImagenSeleccionado.setText("Sin fotografía");

            Object[] filas= {};
            filas = Auto.getListaServiciosRelacionados().toArray();
            System.out.println(Auto.getListaServiciosRelacionados());
            TablaServiciosAsociados.ModificarTablaServiciosAsociados(filas);

            DatosCliente.frameDatosCliente.textNombreCliente.setText("Nombre: "+Persona.getNombreCompleto());
            DatosCliente.frameDatosCliente.textCedula.setText("Cédula: "+Persona.getCedula());
            DatosCliente.frameDatosCliente.textoCorreo.setText("Correo: "+Persona.getCorreoElectronico());
            DatosCliente.frameDatosCliente.textoDireccion.setText("Correo: "+Persona.getDireccionExacta());
            DatosCliente.frameDatosCliente.textoLicencia.setText("Licencia: "+ Persona.getNumeroLicencia() + 
                    " ("+Persona.getTipoLicencia() +") " + "("+ 
                        Utilitaria.formatoFecha(Persona.getFechaEmisionLicencia()) + " - " + 
                            Utilitaria.formatoFecha(Persona.getFechaExpiracionLicencia()) +")");

            imagenSeleccionada = new ImageIcon(Persona.getImagen());
            DatosCliente.frameDatosCliente.img2.setIcon(imagenSeleccionada);
            imagenSinEscala = imagenSeleccionada.getImage();
            imagenEscalada = imagenSinEscala.getScaledInstance(160, 90, Image.SCALE_SMOOTH);
            imagenSeleccionada.setImage(imagenEscalada);
            DatosCliente.frameDatosCliente.img2.setIcon(imagenSeleccionada);
            DatosCliente.frameDatosCliente.img2.setText("Sin fotografía");
            Inicio.VentanaReserva(true);
            frameRegistrarOperador.setVisible(false);
            TextFieldPlaca.setText("");
            ReservasDisponibles.setEnabled(false);
            ReservasDisponibles.setSelectedIndex(0);
        
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConsultarActionPerformed

    private void ReservasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservasDisponiblesActionPerformed

        ReservaSeleccionada=((Reserva)ReservasDisponibles.getSelectedItem());
            // TODO add your handling code here:
    }//GEN-LAST:event_ReservasDisponiblesActionPerformed

    private void TextFieldPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPlacaActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPlacaActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        if(TextFieldPlaca.getText() != ""){
            if (!Inicio.adminApp.filtrarReservaVehiculo(TextFieldPlaca.getText()).isEmpty()) {
                ReservasDisponibles.setEnabled(true);
                DefaultComboBoxModel mod;
                mod = new DefaultComboBoxModel(Inicio.adminApp.filtrarReservaVehiculo(
                        TextFieldPlaca.getText()).toArray());
                ReservasDisponibles.setModel(mod);
            }else{
                JOptionPane.showMessageDialog(this, "No se encuentra un vehículo con esa placa");
            }
        }else{
            ReservasDisponibles.setEnabled(false);
        }    
           

// TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotónAtrás;
    private javax.swing.JComboBox<Reserva> ReservasDisponibles;
    private javax.swing.JTextField TextFieldPlaca;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
