/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controlador.Utilitaria;
import static GUI.FiltroFecha.ReservaSeleccionada;
import static GUI.FiltroPuntoRecogida.frameRegistrarOperador;
import Modelo.Cliente;
import Modelo.Operador;
import Modelo.Reserva;
import Modelo.Vehiculo;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 * Esta clase (Java Form) hereda de JFrame, esta ventana permite al usuario filtrar las reservas
 * por operador realizador.
 * @since 30/10/2020
 * @version 1.0
 * @author Fabricio Delgado Morales, Johan Alonso Calvo Vargas, Mariana Hidalgo Sandoval, 
 * Silvia Melissa Rodríguez Fernández
 * 
 */

public class FiltroOperador extends javax.swing.JFrame {
        static FiltroOperador frameRegistrarOperador = new FiltroOperador();
        static Operador OperadorSeleccionado;
    /**
     * Creates new form FiltroPuntoRecogida
     */
    public FiltroOperador() {
        initComponents();
        ReservasDisponibles.setEnabled(false);
        DefaultComboBoxModel mod= new DefaultComboBoxModel(Inicio.listaOperadores.toArray());
        OperadoresComboBox.setModel(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        BotónBuscar = new javax.swing.JButton();
        BotonConsultar = new javax.swing.JButton();
        OperadoresComboBox = new javax.swing.JComboBox<>();
        ReservasDisponibles = new javax.swing.JComboBox<>();
        BotónAtrás1 = new javax.swing.JButton();

        jToggleButton2.setText("jToggleButton2");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 250));

        BotónBuscar.setText("Buscar");
        BotónBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotónBuscarActionPerformed(evt);
            }
        });

        BotonConsultar.setText("Consultar");
        BotonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultarActionPerformed(evt);
            }
        });

        OperadoresComboBox.setModel(new javax.swing.DefaultComboBoxModel<>());
        OperadoresComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperadoresComboBoxActionPerformed(evt);
            }
        });

        ReservasDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","Item 1", "Item 2", "Item 3", "Item 4" }));
        ReservasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservasDisponiblesActionPerformed(evt);
            }
        });

        BotónAtrás1.setText("Atrás");
        BotónAtrás1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotónAtrás1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotónAtrás1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReservasDisponibles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(OperadoresComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotónBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(BotónAtrás1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OperadoresComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotónBuscar))
                .addGap(18, 18, 18)
                .addComponent(ReservasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonConsultar)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarActionPerformed
        if(OperadoresComboBox.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "No hay un operador seleccionado");
        } else{
            ReservaSeleccionada = (Reserva) ReservasDisponibles.getSelectedItem();
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

            DatosCliente.frameDatosCliente.setLocation(dim.width/2-
                    DatosCliente.frameDatosCliente.getSize().width/2, dim.height/2-
                            DatosCliente.frameDatosCliente.getSize().height/2);

            Inicio.VentanaConsultarReserva(false); 
            Inicio.VentanaReserva(true);

            Inicio.frameRes.ContenidoTextoID.setText(String.valueOf(ReservaSeleccionada.getNumeroFactura()));
            Inicio.frameRes.ContenidoTextoRecogida.setText(ReservaSeleccionada.getSedeRecogida());
            Inicio.frameRes.ContenidoTextoEntrega.setText(ReservaSeleccionada.getSedeEntrega());
            Inicio.frameRes.ContenidoTextoInicio.setText(
                    Utilitaria.formatoFecha(ReservaSeleccionada.getFechaInicio()));
            Inicio.frameRes.ContenidoTextoFinal.setText(
                    Utilitaria.formatoFecha(ReservaSeleccionada.getFechaFinalizacion()));
            Inicio.frameRes.ContenidoTextoSolicitud.setText(
                    Utilitaria.formatoFecha(ReservaSeleccionada.getFechaSolicitud()));
            Inicio.frameRes.ContenidoTextoOperador.setText(ReservaSeleccionada.getOperador().toString());
            Vehiculo Auto = ReservaSeleccionada.getVehiculoSeleccionado();
            Cliente Persona = ReservaSeleccionada.getClienteRelacionado();
            Inicio.frameRes.ContenidoTextoCliente.setText(ReservaSeleccionada.getClienteRelacionado().toString());
            TablaServiciosReserva.frameTablaServiciosPorReserva.agregarServicios
                (ReservaSeleccionada.getArrayServicios());
            Detalles.TextoPlacaSeleccionado.setText(Auto.getPlaca());
            Detalles.TextoAñoSeleccionado.setText(String.valueOf(Auto.getAñoFabricacion()));
            Detalles.TextoColorSeleccionado.setText(Auto.getColor());
            Detalles.TextoMarcaSeleccionado.setText(Auto.getMarca());
            Detalles.TextoKilometrajeSeleccionado.setText(String.valueOf(Auto.getKilometraje()));
            Detalles.TextoKCapacidadSeleccionado.setText(String.valueOf(Auto.getCapacidad()));
            Detalles.TextoPuertasSeleccionado.setText(String.valueOf(Auto.getNumeroPuertas()));
            Detalles.TextoMPGSeleccionado.setText(String.valueOf(Auto.getMpg())); 
            Detalles.TextoSedeSeleccionado.setText(Auto.getSede());
            Detalles.TextoCostoeleccionado.setText(String.valueOf(Auto.getCostoDiario())+"/d");
            Detalles.TextoCapacidadSeleccionado.setText(String.valueOf(Auto.getCapacidad()));
            Detalles.TextoTipoTransimisionSeleccionado.setText(Auto.getTipoTransmision().toString());
            Detalles.TextoEstadoSeleccionado.setText(Auto.getEstado().toString());
            Detalles.TextoVinSeleccionado.setText(Auto.getNumeroVin().toString());

            ImageIcon imagenSeleccionada = new ImageIcon(Auto.getImagen());
            Detalles.TextoImagenSeleccionado.setIcon(imagenSeleccionada);
            Image imagenSinEscala = imagenSeleccionada.getImage();
            Image imagenEscalada = imagenSinEscala.getScaledInstance(256, 144, Image.SCALE_SMOOTH);
            imagenSeleccionada.setImage(imagenEscalada);
            Detalles.TextoImagenSeleccionado.setIcon(imagenSeleccionada);
            Detalles.TextoImagenSeleccionado.setText("Sin fotografía");

            Object[] filas= {};
            filas = Auto.getListaServiciosRelacionados().toArray();
            System.out.println(Auto.getListaServiciosRelacionados());
            TablaServiciosAsociados.ModificarTablaServiciosAsociados(filas);

            DatosCliente.frameDatosCliente.textNombreCliente.setText("Nombre: "+Persona.getNombreCompleto());
            DatosCliente.frameDatosCliente.textCedula.setText("Cédula: "+Persona.getCedula());
            DatosCliente.frameDatosCliente.textoCorreo.setText("Correo: "+Persona.getCorreoElectronico());
            DatosCliente.frameDatosCliente.textoDireccion.setText("Correo: "+Persona.getDireccionExacta());
            DatosCliente.frameDatosCliente.textoLicencia.setText("Licencia: "+ Persona.getNumeroLicencia() + 
                    " ("+Persona.getTipoLicencia() +") " + "("+ 
                        Utilitaria.formatoFecha(Persona.getFechaEmisionLicencia()) + " - " + 
                            Utilitaria.formatoFecha(Persona.getFechaExpiracionLicencia()) +")");

            imagenSeleccionada = new ImageIcon(Persona.getImagen());
            DatosCliente.frameDatosCliente.img2.setIcon(imagenSeleccionada);
            imagenSinEscala = imagenSeleccionada.getImage();
            imagenEscalada = imagenSinEscala.getScaledInstance(160, 90, Image.SCALE_SMOOTH);
            imagenSeleccionada.setImage(imagenEscalada);
            DatosCliente.frameDatosCliente.img2.setIcon(imagenSeleccionada);
            DatosCliente.frameDatosCliente.img2.setText("Sin fotografía");
            Inicio.VentanaReserva(true);
            frameRegistrarOperador.setVisible(false);
            OperadoresComboBox.setSelectedIndex(0);
            ReservasDisponibles.setEnabled(false);
        
        
        }
    }//GEN-LAST:event_BotonConsultarActionPerformed

    private void OperadoresComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperadoresComboBoxActionPerformed

    }//GEN-LAST:event_OperadoresComboBoxActionPerformed

    private void BotónBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotónBuscarActionPerformed
        if(OperadoresComboBox.getSelectedItem() != ""){
            ReservasDisponibles.setEnabled(true);
            Operador O = (Operador)OperadoresComboBox.getSelectedItem();
            DefaultComboBoxModel mod;
            mod = new DefaultComboBoxModel(Inicio.adminApp.filtrarReservaOperador(O.getNombreCompleto()).toArray());
            ReservasDisponibles.setModel(mod);
        }else{
            ReservasDisponibles.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BotónBuscarActionPerformed

    private void ReservasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservasDisponiblesActionPerformed

            OperadorSeleccionado=((Operador)OperadoresComboBox.getSelectedItem());        // TODO add your handling code here:
    }//GEN-LAST:event_ReservasDisponiblesActionPerformed

    private void BotónAtrás1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotónAtrás1ActionPerformed
        frameRegistrarOperador.setVisible(false);
        ReservasDisponibles.setEnabled(false);
    }//GEN-LAST:event_BotónAtrás1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConsultar;
    private javax.swing.JButton BotónAtrás1;
    private javax.swing.JButton BotónBuscar;
    private javax.swing.JComboBox<Operador> OperadoresComboBox;
    private javax.swing.JComboBox<String> ReservasDisponibles;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
